### ISSUE TITLE
kp:volume-down and kp:volume-up aren't working on 10.10.2

### ISSUE THREAD

**Issue by kevinyuliawan** [BlueM/cliclick#16]
As the title suggests, the keypress functions aren't working for the volume options (I'm on a Macbook Air 10.10.2)

**Comment by BlueM** [comment]
I can reproduce that. In fact, I’ve never tested these keys, but simply relied on the comment “keycodes for keys that are independent of keyboard layout” in `/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Headers/Events.h`. It turns out that – at least for the volume keys – the comment should be read as “will never work, regardless of keyboard layout” ;-)

Chances are that I’ll be able to comit a fix within the next week.

**Comment by BlueM** [comment]
Could you verify that it works for you with the latest commit?

**Comment by burtontanner** [comment]
@BlueM volume up and down work for me but I cannot get play-next or play-previous to work.
