### ISSUE TITLE
Command "t" returns segmentation fault

### ISSUE THREAD

**Issue by xream** [BlueM/cliclick#25]
OS: 10.11
<img width="762" alt="2015-10-05 04 36 48" src="https://cloud.githubusercontent.com/assets/1210282/10270100/b6eff4d4-6b1a-11e5-8f78-caf3fada1b1f.png">

**Comment by BlueM** [comment]
I am not able to reproduce this, neither on 10.10 or on 10.11.

Questions:
* Did this happen with a release from my website or with a version compiled from the current master?
* What keyboard layout do you use?
* Can you type anything using `t`, or does cliclick always crash?

**Comment by xream** [comment]
- Did this happen with a release from my website or with a version compiled from the current master?

I use homebrew.

❯ brew info cliclick
cliclick: stable 3.1
Tool for automating emulated mouse clicks
https://www.bluem.net/jump/cliclick/
/usr/local/Cellar/cliclick/3.1 (4 files, 104K) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cliclick.rb


- What keyboard layout do you use?

I use the default macbook keyboard layout which is english I think. Maybe I misunderstand your question, please let me know.


- Can you type anything using t, or does cliclick always crash?

I can use other commands like "c", "kp", etc.
Only the "t" command crash.

Thank you for your time!

**Comment by BlueM** [comment]
Thanks for the answers.

Regarding the keyboard layout: yes, this was what I was asking for. But it would be nice if you could provide the exact name of the keyboard layout, as there are various English layouts. You will find that information in System Preferences -> Keyboard -> Input Sources.

**Comment by xream** [comment]
I'm using a Chinese input source.
Command "t" works when I change it back to English.

**Comment by BlueM** [comment]
And which one exactly? There are traditional and simplified layouts, for each of which there are several variations available.

**Comment by xream** [comment]
I just test every one in Chinese traditional and simplified layouts. And they all crash.

**Comment by BlueM** [comment]
I found the reason for the crash and a way to work around it, but I’m not sure how to enter non-Chinese text with it.

For testing, I chose “Pinyin – Traditional” as the keyboard layout. Now, whenever I type something (be it in Terminal or somewhere else, for instance: TextEdit), a drop-down appears, offering Chinese glyphs. See this example, where I tried to simply enter “cliclick”, and was not able to:
![chinese](https://cloud.githubusercontent.com/assets/1493457/10559651/7583a6ae-74f6-11e5-9caa-5d1f0eb2f333.png)
In this example, after typing a space, the input string was transformed to some Chinese word or phrase.

It does not make a difference whether I type manually on the physical keyboard or via cliclick – in either case, I am not able to type something as simple as your `cliclick t:'ls -l' kp:return` example. Just for testing, I chose another layout (“Wubi Xing”), and I get a different autocompletion panel, but the problem is the same.

So for the moment my question is: how does using Terminal work with a Chinese layout? Can this autocomplete be suppressed?

**Comment by xream** [comment]
I ran the command in terminal and it crashed.

<img width="682" alt="2015-10-17 23 56 36" src="https://cloud.githubusercontent.com/assets/1210282/10559796/cfc06b3c-752a-11e5-8108-3b383c5a5bae.png">

**Comment by BlueM** [comment]
Yes, I know.

Did you read and understand my last comment?

**Comment by xream** [comment]
I'm sorry. I just understand you last comment.

- How does using Terminal work with a Chinese layout? Can this autocomplete be suppressed?

- I usually use English layout when I type in Terminal. When the autocompletion panel comes out, you can press enter to end it and the output is the original letters you typed.

BTW, if I ran the code in Script Editor.app with Chinese layout, it crashed too.

<img width="812" alt="2015-10-18 00 07 13" src="https://cloud.githubusercontent.com/assets/1210282/10559863/39684c20-752c-11e5-88c6-793e3988c785.png">
<img width="812" alt="2015-10-18 00 07 09" src="https://cloud.githubusercontent.com/assets/1210282/10559864/396da120-752c-11e5-853f-49aecd62fe06.png">

**Comment by driven** [comment]
I have used /opt/X11/bin/setxkbmap  for this type of thing before...

not sure if theres a none X11 version...

**Comment by BlueM** [comment]
The crash is fixed with that commit.

However, I’m not sure if it will be usable for real-life scripting, as the “autocompletion” for Chinese characters makes entering shell commands difficutl or impossible. You can always add a `kp:enter` after typing to suppress the autocompletion, but there are cases where even that doesn’t seem to work.

**Comment by BlueM** [comment]
@driven: Interesting suggestion – I didn’t know setxkbmap before. Unfortunately, I don’t know a way of changing the keyboard layout programmatically, especially as it would have to be a method that can also be applied when cliclick is not invoked in Terminal, but also from AppleScript or any scripting language.

**Comment by linuxsong** [comment]
I have the same problem In OS X 10.11 with Chine input method.

**Comment by BlueM** [comment]
I have to admit that http://pinyin.sogou.com/mac/wubi.php does not make much sense to me. I don’t understand Chinese, and the English translation is pretty bizarre. (And my missing understanding of typing Chinese is probably also not helpful.)

**Comment by linuxsong** [comment]
I checkout  the source code from branch master and build it,the run ./cliclick t:sometext  with Chinese input works ok!
Before I get cliclick use brew, may be that build has some problem with Chinese input method.
Thanks BlueM.Good job!

**Comment by BlueM** [comment]
The fix is in master, but not yet released. So, the version available via Homebrew, MacPorts and the build available from my website still has that bug.
