### ISSUE TITLE
Sending shortcut

### ISSUE THREAD

**Issue by romanvbabenko** [BlueM/cliclick#35]
Just have not found how to ask question, so the question is: how to send shortcut into active windows e.g. ALT+CMD+I, to open Google Chrome Development Tools
Thanks

**Comment by BlueM** [comment]
Could be done like this (assumed the target application is already in the foreground):
`cliclick -w 100 kd:alt,cmd t:i ku:alt,cmd`

This means: alt + cmd keys down, then type “i”, then alt + cmd keys up – and because that would be too fast for Chrome, wait 100 milliseconds (`-w 100`) between each action.
