### ISSUE TITLE
send keypresses faster

### ISSUE THREAD

**Issue by theonlygusti** [BlueM/cliclick#87]
I want to spam the function key.

I can't tell the difference between

    while :; do cliclick kd:fn && sleep .1 && cliclick ku:fn && sleep .1; done

and

    while :; do cliclick kd:fn && cliclick ku:fn; done

They both behave the same.

**Comment by BlueM** [comment]
After executing `cliclick kd:fn`, the cliclick process exits. What happens then is up to macOS, and 
from testing, it looks like the OS is no longer interested in events previously posted by cliclick. In other words: when `sleep .1` is executed, the key down event is no longer relevant.

So if you want to quickly press & release fn (for whatever reason – I don’t quite get what you are trying to do), the better approach would be:

    while :; do cliclick kd:fn w:100 ku:fn w:100; done

**Comment by theonlygusti** [comment]
@BlueM I wonder if there's still a limit, this:

    cliclick kd:fn w:1 ku:fn w:1 kd:fn w:1 ku:fn w:1 kd:fn w:1 ku:fn w:1 kd:fn w:1 ku:fn w:1 kd:fn w:1 ku:fn w:1 kd:fn w:1 ku:fn w:1 kd:fn w:1 ku:fn w:1 kd:fn w:1 ku:fn

feels the same as

     cliclick kd:fn w:20 ku:fn w:20 kd:fn w:20 ku:fn w:20 kd:fn w:20 ku:fn w:20 kd:fn w:20 ku:fn w:20 kd:fn w:20 ku:fn w:20 kd:fn w:20 ku:fn w:20 kd:fn w:20 ku:fn w:20 kd:fn w:20 ku:fn

**Comment by BlueM** [comment]
Not surprising. If cliclick emitted events as fast as it can, it would be too fast for the events to be recognized (not for every event and in every case, but often). Therefore, there is an intentional delay (https://github.com/BlueM/cliclick/blob/master/ActionExecutor.m#L90) between the commands – currently, 100 ms.

If you clone the repository, remove that line and compile it, then it will be as fast as possible.

**Comment by BlueM** [comment]
Closed, as stale for 11 months
